apiVersion: v1
kind: Service
metadata:
  name: azure-calculator
  labels:
    app: azure-calculator
spec:
  type: NodePort
  selector:
    app: azure-calculator
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30500
    protocol: TCP
    name: http
